### ISSUE TITLE
[Bug] Error message when executing Keepass with DarkTheme.plgx: Incompatible Plugin 

### ISSUE THREAD

**Issue by dglms** [xatupal/DarkTheme#1]
OS: Windows 10 Home v. 1803
Keepass Version: 2.41

When using DarkTheme.plgx in the plugins folder, an incompatibility error appears on the screen, screenshot below.
![Error](https://user-images.githubusercontent.com/46732245/54874105-426e5800-4dc3-11e9-9b2b-e5d07884845a.JPG)

When using DarkTheme.dll however, it works without any hiccups.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
![image](https://user-images.githubusercontent.com/46166740/55634829-9283ec00-57bf-11e9-8a64-2bed6d395c7c.png)

**Comment by xatupal** [comment]
Thanks for info and sorry for delay. Sadly, I am not notified by GitHub about new issues.

The problem was solved.
