### ISSUE TITLE
[Bug] Theme incompability with Icon Picker

### ISSUE THREAD

**Issue by BradyThe** [xatupal/DarkTheme#2]
First of all, thank you for creating this plugin. I am very much looking forward to the option to read custom themes.

Now to the problem. The theme styling of tables(?) overwrites the Icon Picker making it unusable.

![KeePass_2019-03-26_10-42-46](https://user-images.githubusercontent.com/8181555/54988443-be7cc180-4fb6-11e9-9de7-5e64b793c6bf.png)
![KeePass_2019-03-26_10-43-08](https://user-images.githubusercontent.com/8181555/54988451-c2a8df00-4fb6-11e9-9984-6fca642e3637.png)

Cheers.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
i can confirm this issue in version v.0.2 still exist see: 
![image](https://user-images.githubusercontent.com/46166740/55662695-22548500-5816-11e9-941c-75ad43603354.png)

**Comment by xatupal** [comment]
Thanks for info and sorry for delay. Sadly, I am not notified by GitHub about new issues.

I will look at this problem.
